# Makefile for terraform-provider-virtualbox
BINARY_NAME    = terraform-provider-virtualbox
GOOS          ?= $(shell go env GOOS)
GOARCH        ?= $(shell go env GOARCH)

# Terraform plugin directory — where `make install` places the binary on macOS/Linux.
PLUGIN_DIR     = $(HOME)/.terraform.d/plugins/registry.terraform.io/bryanbelanger/virtualbox/0.1.0/$(GOOS)_$(GOARCH)
PLUGIN_BINARY  = $(PLUGIN_DIR)/$(BINARY_NAME)

# ~/.terraformrc — dev_overrides so macOS Terraform skips the public registry.
TERRAFORMRC    = $(HOME)/.terraformrc

default: build

.PHONY: build
build:
	go build -o $(BINARY_NAME) .

# install: build the binary, copy it to the Terraform plugin cache, and write
# ~/.terraformrc with dev_overrides so `terraform apply` uses the local binary.
.PHONY: install
install: build
	mkdir -p $(PLUGIN_DIR)
	cp $(BINARY_NAME) $(PLUGIN_BINARY)
	@echo "Provider installed to: $(PLUGIN_BINARY)"
	@printf '# Auto-generated by make install\n#\n# dev_overrides  — used by terraform apply (skips version resolution)\n# filesystem_mirror — used by terraform init (satisfies install from local\n#                     disk when the provider appears in terraform.tfstate,\n#                     preventing "provider registry does not have a provider\n#                     named" errors)\n\nprovider_installation {\n  dev_overrides {\n    "registry.terraform.io/bryanbelanger/virtualbox" = "$(PLUGIN_DIR)"\n  }\n\n  filesystem_mirror {\n    path    = "$(HOME)/.terraform.d/plugins"\n    include = ["registry.terraform.io/bryanbelanger/virtualbox"]\n  }\n\n  direct {\n    exclude = ["registry.terraform.io/bryanbelanger/virtualbox"]\n  }\n}\n' > $(TERRAFORMRC)
	@echo "~/.terraformrc written with dev_overrides for bryanbelanger/virtualbox"
	@echo ""
	@echo "Usage:"
	@echo "  cd ~/Projects/win_ansible_install"
	@echo "  terraform init    # downloads talos, helm, kubernetes, null providers"
	@echo "  terraform apply   # uses local virtualbox provider via dev_overrides"

.PHONY: test
test:
	go test -v ./...

.PHONY: testacc
testacc:
	TF_ACC=1 go test ./... -v $(TESTARGS) -timeout 120m

.PHONY: docs
docs:
	go generate ./...

.PHONY: vet
vet:
	go vet ./...

.PHONY: lint
lint: vet
	staticcheck ./...

.PHONY: clean
clean:
	rm -f $(BINARY_NAME)
	rm -f $(BINARY_NAME).exe

.PHONY: fmt
fmt:
	go fmt ./...

.PHONY: tidy
tidy:
	go mod tidy
	go mod verify

.PHONY: build-all
build-all: build test vet

# dev-install: full cycle — tidy, build, test, install, write ~/.terraformrc
.PHONY: dev-install
dev-install: tidy build test install
	@echo "dev-install complete."